name: Create .env File

on:
  push:
    branches:
      - master

jobs:
  create-env-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env File
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env